# 工作流的名称
name: Build Tweak

# 触发条件
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 任务列表
jobs:
  build:
    # 运行环境：使用最新的 macOS 系统
    runs-on: macos-latest

    # 任务步骤
    steps:
      # 第一步：检出你的代码
      - name: Checkout
        uses: actions/checkout@v4 # <-- 已更新

      # 第二步：安装 Theos 环境 (使用官方维护的 Action)
      - name: Setup Theos
        uses: theos/theos-action@v1 # <-- 已替换为官方版本

      # 第三步：运行 make package 命令进行编译和打包
      - name: Build Package
        run: make package

      # 第四步：上传编译产物 (.deb 文件)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # <-- 已更新
        with:
          name: Tweak-Deb-Package
          path: packages/*.deb
