# 工作流的名称
name: Build Tweak

# 触发条件
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 任务列表
jobs:
  build:
    # 运行环境：使用最新的 macOS 系统
    runs-on: macos-latest

    # 任务步骤
    steps:
      # 第一步：检出你的代码
      - name: Checkout
        uses: actions/checkout@v4

      # 第二步：手动安装 Theos (最稳定的方法)
      - name: Install Theos
        run: |
          # 将 THEOS 环境变量写入 GitHub 的环境变量文件，让后续步骤也能使用
          echo "THEOS=~/theos" >> $GITHUB_ENV
          # 使用 git 克隆 Theos 仓库到指定目录
          git clone --recursive https://github.com/theos/theos.git ~/theos

      # 第三步：运行 make package 命令进行编译和打包
      # 这一步会自动使用上面设置的 $THEOS 环境变量
      - name: Build Package
        run: make package

      # 第四步：上传编译产物 (.deb 文件)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Tweak-Deb-Package
          path: packages/*.deb
